export const button: string;
export const input: string;
export const inputButton: string;
export const inputWrapper: string;
export const paragraph: string;
export const paragraphSecond: string;
export const radioWrapper: string;
export const title: string;
export const token: string;
