export const author: string;
export const authorExpanded: string;
export const cover: string;
export const coverWrapper: string;
export const coverWrapperExpanded: string;
export const songDescriptionWrapper: string;
export const songDescriptionWrapperExpanded: string;
export const title: string;
export const titleExpanded: string;
